import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getUsuarioActual } from "@/lib/usuario";
import { prisma } from "@/lib/prisma";
import { NotificacionesBell } from "@/components/notificaciones-bell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const usuario = await getUsuarioActual();
  const notificaciones = usuario
    ? await prisma.notificacion.findMany({
        where: { usuarioDestinoId: usuario.id },
        orderBy: { fechaCreacion: "desc" },
        take: 20,
      })
    : [];

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {usuario && <NotificacionesBell notificaciones={notificaciones} />}
        {children}
      </body>
    </html>
  );
}
